name: Build Image and Update Chart Version

on:
  push:
    tags:
      - "v*"

jobs:
  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for Git operations

      # Extract version from Git tag
      - name: Extract version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/metrics-test:${{ env.VERSION }}


  update-helm:
    name: Update Helm Chart Version
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0  # Full history for Git operations

      # Extract version from Git tag
      - name: Extract version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      # Update Helm chart version
      - name: Update Helm Chart
        run: |
          sed -i "s/^version:.*/version: ${{ env.VERSION }}/" charts/test-chart/Chart.yaml

      # Push the Chart.yaml changes to the repo
      - name: Update the chart version
        env:
          GITHUB_TOKEN: ${{ secrets.HELM_TRIGGER_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add charts/test-chart/Chart.yaml
          git commit -m "Update Helm chart version to ${{ env.VERSION }}"
          git push https://x-access-token:${{ secrets.HELM_TRIGGER_TOKEN }}@github.com/brsoper/test-metrics.git main


  trigger:
    name: Trigger Helm Release
    runs-on: ubuntu-latest
    needs: update-helm
    steps:
      # Send trigger to helm-chart repo
      - name: Send Repository Dispatch Event
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.HELM_TRIGGER_TOKEN }}" \
               -H "Accept: application/vnd.github.everest-preview+json" \
               https://api.github.com/repos/brsoper/helm-charts/dispatches \
               -d '{"event_type": "trigger-helm-release"}'
