name: Trigger Helm Chart Release

on:
  push:
    branches:
      - "v*"

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for Git operations

      # Extract version from Git tag
      - name: Extract version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ env.VERSION }}

      # Send trigger to helm-chart repo
      - name: Send Repository Dispatch Event
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.HELM_TRIGGER_TOKEN }}" \
               -H "Accept: application/vnd.github.everest-preview+json" \
               https://api.github.com/repos/brsoper/helm-charts/dispatches \
               -d '{"event_type": "trigger-helm-release"}'
